version: "3.9"
services:
  shop:
    build:
      context: .
      dockerfile: ./shop/src/main/docker/Dockerfile.native
    ports:
      - "8080:8080"
    networks:
      - quarkus
  store:
    build:
      context: .
      dockerfile: ./store/src/main/docker/Dockerfile.native
    ports:
      - "8081:8081"
    networks:
      - quarkus
networks:
  quarkus:
    driver: bridge